notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run build
  - npm run test
  - npm run lint

# Npm publish options
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: Y+nt75BAkBSshHgS/FCjC7BBmtadNyFmcT5PTEjFxneLpW5SBPe/58iUhxkt5xSDZbxr1l7TH+eOgROxmHx13OROuCUcWrK3m4tbHBbiaI3GcQ7hCEfpnqWeUF53seqDabikypttHcYmELJtW1H+il6U2U5YwPDrEuSOGhnmx1yoZOZ6DCXuLSi/JgLhCY9m7AuvckH40B/7kGMad58Df81EKZYM37/icuG85pWgCoJcPIV1XoF3KTl5T9rPn9pxLdx25xBB/P4tjJ7v+gKuiKiVBJTSpTtlJEQCba/1dWNH1q1/305cgJ/16PlMs0yENQxwVxtcyHpXoULHb0WnGf6Y3YsjG23N/b0GFtgC/lvH/+PBmvbinguu4vrSk53gxqPyZX2+vyvHAtcYN2cssVMe0D3RmPC95U24qeNZ3sqo6w8/C7dk+UjkaBs2/6dUxF0buUmE+iyOmCMQgSiphsGgoqtqCus/qt7vxs6LpIHl/AB+HabQFMMDd0vn091HrFZSxErIr7a57xI7eWcMXPC2sfa2xBu1i5pOWEEb7r8lYnkrCuOjN46/d2VlfFDhLMqqOSvykvrIksSTvHthwPzkaTsNq37/rZmzi+rBs57b3Otvo1EEy2Hcop7FcwBUc/BkrFMPrpV16/IO9Z+V7zilny+kOn+WU238oG6ifM8=
  on:
    node: '6'

# SAUCE_TOKENS
env:
  global:
    - secure: Hi3/I7f4hZPBbsdB2TA25ur6d06bohTeS2NTQvzlN4Kyrtoj/praIuYMTNhnNRx9gdMFucm8UluX9gpisYUew0JdEIVfc5BuUWpOjFWxwyxdV/5oJLWEOja+IjsFtPhllJtRopkpTAfMOg5mchBZXZ5+tQo/MYRAO2ezJ26yZVITUa0lC6BSVZeywCqie2dAYFeP+FtLiFVrjWluxhwwccsAxfH7saUDVj6PPgXfKSy2o4DR9TPZ6r5jAPtMxWeupPQYkYF47DZESio/KNUKFergP8PUTNCFAtqNPmfZ+otdhIMsGCp+6dDqMwRwOx7Epn6TcxXOnOjmih78EiJoK5j5dNx5lLsNifXQRAaCy3ac9MtYagKVHwi+HA3PJxBWOEfgIK51IFOjzQ73Rs05B8g6pOGUfbKqpEdnxU7D+oigkm8CvP2mo61n7zWtmrCqu5B+G9QHCrjoXZY5OMgi+cuqM87y15qJ+DNrf3rbMm5HB+3FDuGk75ed/N+j8qpZggyhyvxthkaJtn+V4gMX1CgWsIE3TOsxVFXUSakN1z76eeaNT5gEryfHDEiV1JlOyoPsK6KlJhe5FFtTMCZxLnUvEIhang9I8bWYZgg2+v3CToSINpUVUiq067K8Vp9VBDr15uEp545bw0Ye+TNWsISqiQ39/ViXsrTv+3yvqUE=
    - secure: fhLoAU1XtE3JmZG5TIWCDC06jDETksdZtvRiAXD3oA4RAK7QF0URdZz4UlnrZSQvS76Lf5smrrdMl2Rdk6HIDWPgAh9VCyzDWhVw6tDWQTDbrZ527hdFWVkTHLKxdPe3wWEj41yzWg19wT28LtuULvppm89E1XD/fRUdZQFVRoD3r7BbfH5JfAEZ9J9GHKIIH4eB2k53QhO2zHJorPHLPe4KceYJd7URhRttm0GGy8TnhO69RQZq526KdI+i+yXjp5Tjnmqlejx6sY5hiYdv6sfbyEs+UTDsBv1hWX8Xzc/NBEKnqd6TU0T353+N8CgrGcNkCfnd0pwKmDhCRC9ImPwqUKsRxt4oul8iZK65PIZUETTvUMIGKs7Zb3/NtA2Cxn+jSIrvLLePUgLRVPxAzh21ow/x9HpLMBf1ZinhrPCc8xnGmXgJHHrkaa00dk4dxZ9Hbz0Fwmx8OPS/yc4KUiMK5UMxAY/L/QZdFcv5wJeNHNvN0y3iaRUCfVGl0hwRJ+KkplMKrPJLVr1a7wrMWWg7yPVp/+id/bacq4EaUczomDdt5w39DpBcP+6ixd8Q+mqVbQBtjTpQE2Dmlgl9Ag55jG8wW5qDyHvfAnAbZuCSdO0bNUI5sPIJvrl01V19IyRZIM2DiFrYjAUzGHatK5VoNc83Hx5ojQ9KzWSawjo=

# Cloud testing
after_deploy:
  - npm install
  - npm run setup
  - npm run test-cloud
